[project]
name = "udemy-agentic-ai-course"
version = "0.1.0"
description = "Sample code for Udemy agentic AI course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.1.0",
    "ipython>=9.8.0",
    "openai>=2.12.0",
    "pypdf>=6.4.2",
]
